# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: en-GB

reviews:
  path_filters:
    - "!**/*.lock"
    - "!**/dist/**"
    - "!**/node_modules/**"
    - "!frontend/dist/**"
    - "!frontend/package-lock.json"
    - "!**/coverage.xml"
    - "!**/*.min.js"
    - "!**/*.min.css"
  auto_review:
    enabled: false

chat:
  auto_reply: true
