# Configuration file for yamllint.
# Documentation: https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length:
    max: 200
  truthy:
    # uses the key 'on' without quotes which fails the truthy check
    ignore: |
      .github/workflows/docker-publish.yml
      .github/workflows/greetings.yml
      .github/workflows/mega-linter.yml
      .github/workflows/semantic-pr-title.yml
