# Configuration file for yamllint.
# Documentation: https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length:
    max: 200
  truthy:
    ignore: |
      .github/workflows/docker-build.yml
      .github/workflows/greetings.yml
      .github/workflows/mega-linter.yml
      .github/workflows/production-smoke-test.yml
      .github/workflows/release-please.yml
      .github/workflows/semantic-pr-title.yml
      .github/workflows/tests.yml
