"""
Unit tests for container identity and monitoring selection.

The stable identifier is the key that restart counts, cooldowns, backoff and
quarantine are all recorded against, so it defines the monitoring identity of a
container across recreations.
"""

from app.tests.unit.conftest import make_container


class TestStableIdentifier:
    """``MonitoringEngine.get_stable_identifier`` priority order."""

    def test_monitoring_id_label_takes_priority(self, engine):
        _, info = make_container(
            name="autogenerated_name_1234",
            labels={
                "autoheal": "true",
                "monitoring.id": "my-service",
                "com.docker.compose.project": "stack",
                "com.docker.compose.service": "web",
            },
        )

        assert engine.get_stable_identifier(info) == "my-service"

    def test_compose_project_and_service_used_when_no_monitoring_id(self, engine):
        _, info = make_container(
            name="stack-web-1",
            labels={
                "autoheal": "true",
                "com.docker.compose.project": "stack",
                "com.docker.compose.service": "web",
            },
        )

        assert engine.get_stable_identifier(info) == "stack_web"

    def test_falls_back_to_container_name(self, engine):
        _, info = make_container(name="lonely-container", labels={"autoheal": "true"})

        assert engine.get_stable_identifier(info) == "lonely-container"

    def test_partial_compose_labels_fall_back_to_name(self, engine):
        _, info = make_container(
            name="stack-web-1",
            labels={"autoheal": "true", "com.docker.compose.service": "web"},
        )

        assert engine.get_stable_identifier(info) == "stack-web-1"

    def test_empty_info_yields_none(self, engine):
        """A disappeared container inspects to ``{}``; that must not raise."""
        assert engine.get_stable_identifier({}) is None

    def test_identifier_survives_container_recreation(self, engine):
        """Recreating a container changes its ID but not its monitoring identity."""
        labels = {
            "autoheal": "true",
            "com.docker.compose.project": "stack",
            "com.docker.compose.service": "web",
        }
        _, old_info = make_container(name="stack-web-1", container_id="a" * 64, labels=labels)
        _, new_info = make_container(name="stack-web-1", container_id="c" * 64, labels=labels)

        assert old_info["full_id"] != new_info["full_id"]
        assert engine.get_stable_identifier(old_info) == engine.get_stable_identifier(new_info)


class TestShouldMonitorContainer:
    """``MonitoringEngine.should_monitor_container`` filtering behaviour."""

    def test_label_matching_container_is_monitored_by_default(self, engine):
        container, info = make_container(labels={"autoheal": "true"})

        assert engine.should_monitor_container(container, info) is True

    def test_container_without_label_is_not_monitored(self, engine):
        container, info = make_container(labels={})

        assert engine.should_monitor_container(container, info) is False

    def test_include_all_monitors_unlabelled_containers(self, engine, update_config):
        update_config(lambda c: setattr(c.monitor, "include_all", True))
        container, info = make_container(labels={})

        assert engine.should_monitor_container(container, info) is True

    def test_explicit_exclusion_wins_over_selection(self, engine, update_config):
        container, info = make_container(name="web", labels={"autoheal": "true"})

        def _configure(config):
            config.containers.selected.append("web")
            config.containers.excluded.append("web")

        update_config(_configure)

        assert engine.should_monitor_container(container, info) is False

    def test_explicit_selection_bypasses_label_filter(self, engine, update_config):
        container, info = make_container(name="web", labels={})
        update_config(lambda c: c.containers.selected.append("web"))

        assert engine.should_monitor_container(container, info) is True

    def test_selection_by_stable_id(self, engine, update_config):
        container, info = make_container(
            name="stack-web-1",
            labels={
                "com.docker.compose.project": "stack",
                "com.docker.compose.service": "web",
            },
        )
        update_config(lambda c: c.containers.selected.append("stack_web"))

        assert engine.should_monitor_container(container, info) is True

    def test_blacklist_name_pattern_excludes_container(self, engine, update_config):
        container, info = make_container(name="db-replica-1", labels={"autoheal": "true"})
        update_config(lambda c: c.filters.blacklist_names.append("db-*"))

        assert engine.should_monitor_container(container, info) is False

    def test_whitelist_name_pattern_requires_a_match(self, engine, update_config):
        matching, matching_info = make_container(name="web-1", labels={"autoheal": "true"})
        other, other_info = make_container(name="worker-1", labels={"autoheal": "true"})
        update_config(lambda c: c.filters.whitelist_names.append("web-*"))

        assert engine.should_monitor_container(matching, matching_info) is True
        assert engine.should_monitor_container(other, other_info) is False

    def test_blacklist_label_excludes_container(self, engine, update_config):
        container, info = make_container(labels={"autoheal": "true", "tier": "batch"})
        update_config(lambda c: c.filters.blacklist_labels.append({"tier": "batch"}))

        assert engine.should_monitor_container(container, info) is False

    def test_whitelist_label_requires_a_match(self, engine, update_config):
        matching, matching_info = make_container(
            name="web", labels={"autoheal": "true", "tier": "prod"}
        )
        other, other_info = make_container(
            name="worker", labels={"autoheal": "true", "tier": "dev"}
        )
        update_config(lambda c: c.filters.whitelist_labels.append({"tier": "prod"}))

        assert engine.should_monitor_container(matching, matching_info) is True
        assert engine.should_monitor_container(other, other_info) is False
